### ISSUE TITLE
Show amount after fees when sweeping wallet

### ISSUE THREAD

**Issue by kilrau** [Blockstream/green_qt#100]
### Description

Here I'd love to see the final amount being sent after network fee is deducted. Usually wallets show min available balance and send amount. Boltz requires exact amounts so this is incredibly hard to do with Green Desktop when sweeping the wallet. I suspect a lot of our "send too little" failure cases are because of this. Pretty bad since these need to be manually refunded by users.

![Screenshot from 2023-12-22 20-25-18](https://github.com/Blockstream/green_qt/assets/19181985/d3a36abd-915e-489d-bac1-7722087972c7)

### Version

1.2.9

### Steps to reproduce

Open green, liquid wallet, send -> send all

**Comment by kilrau** [comment]
On mobile (Android) it shows me all three values
1. Available balance
2. Network fee
3. Send amount

![IMG_20231222_210340](https://github.com/Blockstream/green_qt/assets/19181985/de032c74-2f8b-4d4b-b1fe-3d3d58928d6e)

**Comment by jgriffiths** [comment]
@kilrau The android behaviour shows this is not a gdk issue, likely just a display issue with the qt wallet. Should be easily fixed when the wallet devs are back from xmas break.

**Comment by kilrau** [comment]
bump

**Comment by domegabri** [comment]
@kilrau sneak peek of the UI changes for next release. This should address your request (ignore the fiat amounts as its testnet and conversion rate is fake

<img width="489" alt="Screenshot 2024-01-26 alle 13 11 01" src="https://github.com/Blockstream/green_qt/assets/42006886/b88daeda-586d-49d2-8603-13f14530baf9">

**Comment by borgbyte** [comment]
@kilrau please check latest release.
