### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by 106Madara** [Blockstream/green_qt#104]
"I wanted to create a second wallet with a passphrase and use it as my main wallet. The issue I see is that this second wallet, where I have the additional passphrase, is still visible on the interface. I want this second 'secret' wallet to be invisible, so that in case of any situation, no one can see that I have a second wallet. It would be great if there was a way to make a wallet invisible.

It would be a good feature if the wallet with a passphrase were not visible during login. In the unfortunate event of a robbery, the thief would still see two wallets – one with fewer satoshis and one with more satoshis. They would notice that I have two wallets, and it would be beneficial if the second wallet with a passphrase were not visible when I plug in the Jade and try to log in. In that case, the thief won't see that I have more satoshis on the wallet protected only by a code, without a passphrase. In other words, he sees only one wallet and doesn't realize that I have an additional wallet with a passphrase.

**Comment by borgbyte** [comment]
Latest versions support BIP39 passphrase login

<img width="1013" alt="image" src="https://github.com/Blockstream/green_qt/assets/47895400/1e2c72f7-d6c7-4245-a238-fd0969330d76">

and it doesn't add multiple entries in the wallet list.

is this what you want?
