### ISSUE TITLE
Menu items are not displayed

### ISSUE THREAD

**Issue by MButcho** [Blockstream/green_qt#106]
### Description

After I open app and login to Jade, none of the menu items with 3 dots are displayed.

### Version

v1.2.9

### Steps to reproduce

It happens every time I start the application

### Expected behaviour

See menu items

### Actual behaviour

I see empty screen / menu

### Screenshots

![image](https://github.com/Blockstream/green_qt/assets/41790777/0a15bf60-95b5-46bc-af3e-378c9d3c5411)

### Device or machine

Windows 11

### Additional info

**Comment by borgbyte** [comment]
thanks for the report, will look into this.

**Comment by MButcho** [comment]
> thanks for the report, will look into this.

Any update?

**Comment by borgbyte** [comment]
@MButcho please check latest release.
