### ISSUE TITLE
Add loading indicator for wallet restore

### ISSUE THREAD

**Issue by kilrau** [Blockstream/green_qt#107]
### Description

Last step of Restoring a wallet might take a couple of seconds. It is missing a loading indicator or sth that tells me "it's working"

### Version

1.2.9

### Steps to reproduce

Restore Wallet

### Expected behaviour

Spinner or sth that tells me it's doing sth

### Actual behaviour

"Frozen" Window

### Screenshots

![image](https://github.com/Blockstream/green_qt/assets/19181985/f577ddbf-83c8-4a44-a7e1-66fa6a477b27)

### Device or machine

ubuntu 22.04. Desktop

**Comment by borgbyte** [comment]
@kilrau please check latest release.
