### ISSUE TITLE
Notifications in Liquid Wallet not remembered

### ISSUE THREAD

**Issue by klauslovgreen** [Blockstream/green_qt#11]
### Description

When enabling email Notifications for Sent and Received in General Settings and hit the X on the top right, the settings are not stored.  

### Version

0.0.1-beta2

### Steps to reproduce

Try as described above

### Expected behaviour

Settings to be stored

### Actual behaviour

Settinngs not stored

### Screenshots

n/a

### Device or machine

macOS Catalina 10.15.3

**Comment by domegabri** [comment]
I think those settings are not entirely supported at the moment. better settings handling comes in the next beta

**Comment by domegabri** [comment]
fixed in 24264d96dc03ea9e8462f8c9276813dada83aac0
