### ISSUE TITLE
Blockstream Green v2.0.0 does not start - Windows 11

### ISSUE THREAD

**Issue by NaabKing** [Blockstream/green_qt#112]
### Description
Blockstream Green v2.0.0 does not start anymore.

After updating from v1.2.9 to v2.0.0 app does not start anymore, uninstalling and installing does not help either, had to go back to v1.2.9. I'm using Windows 11 with latest Update.
### Steps to reproduce
Double click the app icon.

### Expected behaviour
App should open.

### Actual behaviour
Nothing happens.

Nothing happens, no process is started (Task manager).
### Device or machine

PC, Windows 11.

**Comment by borgbyte** [comment]
@NaabKing please try 2.0.1.
