### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by RD1974** [Blockstream/green_qt#113]
### Description

Ububtu installation doesn't work !

### Version
Ubuntu 22.04.4 LTS
green 

### Steps to reproduce

- extracted file from tar.gz file (green) doesn't run
- running the command "sudo appt install green" produces the error message "unable to locate package green" !

### Screenshots

![right click](https://github.com/Blockstream/green_qt/assets/163040591/cce813e7-d1e2-4778-aaba-c0aabcb57b05)

![sudo command](https://github.com/Blockstream/green_qt/assets/163040591/330a8ea5-6806-48b7-9dc5-03dc13c71fd0)

**Comment by RD1974** [comment]
installation file : BlockstreamGreen-linux-x86_64.tar.gz

**Comment by borgbyte** [comment]
green is not in ubuntu package repository, so don't bother with `apt install ...`.

after extracing the `.tar.gz` file, run on the command line  `./green` and share the output.

if that fails, please check if you have `libxcb-cursor0` pakcage installed.

**Comment by RD1974** [comment]
Thank you , it was missing the libxcb-cursor0 package and now it is working !
As a suggestion, I think you should include a quick step by step instruction in the package because I couldn't find anything on the internet.

regards,
________________________________

**Comment by borgbyte** [comment]
Thanks for the suggestion.
