### ISSUE TITLE
Green wallet 2.0.1 MacOs Desktop displaying warning icon on recent confirmed transactions.

### ISSUE THREAD

**Issue by jtashiro** [Blockstream/green_qt#115]
### Description
Green support team, I have installed Green 2.0.1 Wallet MacOs Desktop and I'm seeing  warning icon on recent confirmed transactions?  What is that about?

### Version
MacOs
2.0.1

### Steps to reproduce
On the transaction screen, new received transactions post-upgrade have a warning icon with red exclamation point though the transactions are confirmed on blockchain.

### Expected behaviour
Would not expect to see a Warning icon.

### Actual behaviour
Warning icon

### Screenshots

<img width="689" alt="Screenshot 2024-03-12 at 12 57 18 PM" src="https://github.com/Blockstream/green_qt/assets/6698245/e098886c-74e5-4ff6-bb03-8cefdd9540b3">

### Device or machine
Mac OS Ventura 13.6.5

### Additional info
Looks to have been introduced in release 2.x of wallet in qml/TransactionDelegate.qml  line 28, 29.

Did not see this icon on prior version of Green Wallet.

**Comment by borgbyte** [comment]
@jtashiro you have SPV verification enabled. Do you have a custom electrum server?

**Comment by jtashiro** [comment]
No, didn't realize that I needed to have custom electrum server for SPV verification ... when I disable SPV verification in the Settings tab, the warning icon remains on the transactions ... is that a permanent warning going to remain in the UI view?

**Comment by borgbyte** [comment]
> No, didn't realize that I needed to have custom electrum server for SPV verification ...

No, you don't need a custom electrum server, I'm just asking to figure out the issue.

If you disable SPV, you need to logout/login or restart the app. After this, the icon should not be visible. Let me know otherwise.

**Comment by jtashiro** [comment]
The screen timeout occurred and when I entered PIN I am seeing clean transactions now (no warning icon) - thank you.

Now I have to ask what is SPV - is that Blockstream specific feature?

**Comment by borgbyte** [comment]
> The screen timeout occurred and when I entered PIN I am seeing clean transactions now (no warning icon) - thank you.

We will review these icons.

> Now I have to ask what is SPV

See https://electrum.readthedocs.io/en/latest/spv.html

**Comment by jtashiro** [comment]
Are you tracking this as a bug in the UI when SPV is enabled and there are no custom electrum servers in use?
