### ISSUE TITLE
Balance wont update after log in

### ISSUE THREAD

**Issue by Funman2** [Blockstream/green_qt#116]
### Description

Balance won´t update, Fiat Price not electable

### Version

2.0.2, Jade 1.0.28 , cusom blind oracle on umbrel

### Steps to reproduce
try to log in with personal electrum server and tor, balance won´t update, circle always spinning, no fiat price shown.

### Expected behaviour

It used to work with all versions  until 1.0.9 then new version does not work on windows and linux

**Comment by domegabri** [comment]
did you enable tor and set a proxy to connect in network settings of the app?

**Comment by Funman2** [comment]
I enabled Tor and personal electrum server plus verification. 
No proxy.

**Comment by Funman2** [comment]
But running tor as a service on Linux and windows.

**Comment by borgbyte** [comment]
@Funman2 please update to 2.0.3.

**Comment by Funman2** [comment]
Only problem is if i create a watch only, it always shows empty and says I have to create a wallet..when I try it is not possible with Bitcoin single sig

**Comment by Funman2** [comment]
Solved in latest release!
