### ISSUE TITLE
Connect through TOR settings not stored when closing the app 

### ISSUE THREAD

**Issue by klauslovgreen** [Blockstream/green_qt#12]
### Description

Connect through TOR settings not stored when closing the app 

### Version

0.0.1 beta 2

### Steps to reproduce

Enable Connect through TOR in Settings and login - then logout and close app - when you restart the app the setting is reset.

### Expected behaviour

Setting to be saved

### Actual behaviour

Reset

### Screenshots

n/a
### Device or machine

macOS Catalina 10.15.3

**Comment by domegabri** [comment]
thanks for reporting

**Comment by domegabri** [comment]
fixed in 284cb1ddc17b60ce102be4904426068305d2b1ec
