### ISSUE TITLE
Watch only log in with Green Desktop does not work

### ISSUE THREAD

**Issue by Funman2** [Blockstream/green_qt#120]
### Description

when i am logged in with Jade, i created a watch only log in, when i tried to log in there, it only loads an empty wallet, dialogue shows to make my fist receive wallet, when i try to do this i cant create a native segwit wallet. It never updates and never shows my funds.

### Version
2.0.3

### Steps to reproduce

Connect to umbrel node via tor, log in with jade,when all wallets are shown, then create a watch only log in for that wallet

### Expected behaviour
watch only log in to my jade wallet without connecting jade.

### Actual behaviour

shows empty wallet , never updates, same when connected with blockstream backend.

### Screenshots

![Bildschirmfoto vom 2024-03-29 14-00-50](https://github.com/Blockstream/green_qt/assets/105175715/36002473-898f-43a1-bc3d-70a7fbca6ee7)
![Bildschirmfoto vom 2024-03-29 14-01-06](https://github.com/Blockstream/green_qt/assets/105175715/daedede6-e0b3-43e7-a9f2-5d4c3388ae0f)

### Device or machine
Linux and windows 10, same behavior

**Comment by borgbyte** [comment]
ATM watchonly (username and password) is just for multisig.

**Comment by Funman2** [comment]
Thanks
