### ISSUE TITLE
Send & Receive buttons not clickable on all tabs - v2.0.3 arm64 MacOS Sonoma 

### ISSUE THREAD

**Issue by goodc0re** [Blockstream/green_qt#122]
### Description

Send & Receive buttons not clickable, they are visible but seem to be in the background on all tabs 

### Version

v2.0.3 arm64 MacOS Sonoma 

### Steps to reproduce

install, open Blockstream Green, try to click Send or Receive button on any tab (Transactions, Addresses, Coins, Assets)

### Expected behaviour

Upon clicking Send button, get to the send screen and upon clicking Receive, get a new receive address. 

### Actual behaviour

Upon clicking either button, the actual background behind the button is being clicked, be it a certain transaction on the Transactions screen, an Address on the Addresses screen, a coin on the Coins screen, an asset on the Assets screen, or no action if nothing is behind the buttons. 

### Screenshots
<img width="422" alt="Screenshot 2024-03-30 at 12 50 22 PM" src="https://github.com/Blockstream/green_qt/assets/2564288/75a07334-c454-4617-96e5-1fbde4bceabd">

### Device or machine

MacOS Sonoma M3 Max

**Comment by borgbyte** [comment]
How did you login?

**Comment by goodc0re** [comment]
Logging in with JADE. 

The send and receive buttons are working again in the latest version Release 2.0.4

**Comment by borgbyte** [comment]
fixed in 2.0.6.
