### ISSUE TITLE
2FA Authenticator QR codes

### ISSUE THREAD

**Issue by amcitaly** [Blockstream/green_qt#123]
### Description
When I try to add as 2FA the google authenticator the app does not reconnize the qr code, I have tried also with other authenticator apps but nothing

### Version
2.0.3

### Steps to reproduce
Make 2fa protected wallet and try to add as 2fa methotd the authenticator

### Device or machine
Linux 

Intel

### Additional info
Before was working, I add in another wallet

**Comment by borgbyte** [comment]
@amcitaly I confirm the bug, will be fixed in the next patch release.

**Comment by borgbyte** [comment]
@amcitaly please try 2.0.4.

**Comment by amcitaly** [comment]
Is working @borgbyte, thank you!
