### ISSUE TITLE
Feature request: scramble keypad as an option

### ISSUE THREAD

**Issue by maximusmaximalistus** [Blockstream/green_qt#124]
It will be nice to have an option to scramble the keypad both in android an desktop versions.

The labels in the repo aren't available. This is a feature request.

**Comment by alessandro-saglimbeni** [comment]
Hey @maximusmaximalistus, on Android that's already available, on the bottom left of the PIN pad:

![photo_2024-04-24_09-44-05](https://github.com/Blockstream/green_qt/assets/22540533/bbb35fb2-40fe-486e-a76e-44cc4e8a36e5)

**Comment by borgbyte** [comment]
Implemented in 8e79d7184a0e75b4df40d7cd92dff1cd8cc4355c, will be available in the next release.
