### ISSUE TITLE
Feature request: Please add a standalone QR Pin unlock function to the app.

### ISSUE THREAD

**Issue by xGnoSiSx** [Blockstream/green_qt#126]
or provide a standalone small app.

There are many, many cases for this. And I would like *not* to use a web browser, nor to connect to the device with USB.

Also on tailsOS, and perhaps some other linux security distros, camera is deactivated for the browsers by default.

**Comment by borgbyte** [comment]
this experimental feature has landed on master and will be available in the next release.

**Comment by borgbyte** [comment]
available in 2.0.6.
