### ISSUE TITLE
Rename of accounts in Watchonly

### ISSUE THREAD

**Issue by Funman2** [Blockstream/green_qt#128]
### Description

Rename of accounts option is missing in Green Desktop for Linux when using watchonly accounts( AppImage)

Password Login missing

**Comment by borgbyte** [comment]
> Rename of accounts option is missing in Green Desktop for Linux when using watchonly accounts

not possible in watchonly

> Password Login missing

what do you mean?

**Comment by Funman2** [comment]
ah i see, thanks, just because it is possible to set a pin login for the watchonly wallet in green android and also possible to set unique names for the wallets. So options like this would be great and practical in desktop as well.

**Comment by borgbyte** [comment]
Correct me if I'm wrong, you want to rename a watchonly wallet before login?

**Comment by Funman2** [comment]
No🤣I want to be able to rename them after losing and they are loaded.
Account 1, account 22 so is not very unique...
Changing account names in watchonly does not work.

**Comment by borgbyte** [comment]
Right, this is not possible. Is this a multsig or singlesig watchonly?

**Comment by Funman2** [comment]
Singlesig...
I am using watchonly a lot on android and there you could change account names, it's just very convenient...

**Comment by borgbyte** [comment]
Are you sure you can rename accounts in watchonly on android?

**Comment by Funman2** [comment]
Yes!

**Comment by Funman2** [comment]
Anyway thanks for replying!
