### ISSUE TITLE
No Icon for GUI makes difficult to find in menus

### ISSUE THREAD

**Issue by chrisengel** [Blockstream/green_qt#13]
### Description

Currently the qt GUI has no window icon so when navigating in Linux there is only an empty block that you have to highlight to see that it is Green

### Version

0.0.1-beta3

### Steps to reproduce

Open ./Green and navigate to apps menu and see there is no icon identifying Green

### Expected behaviour

Would expect a clear Green icon associated with the window to make navigation simpler

### Actual behaviour

It's just a blank block that has to be highlighted to see that it is Green

### Screenshots

![image](https://user-images.githubusercontent.com/12490915/75975277-85441580-5ed8-11ea-8fba-21f83fc3eac0.png)

### Device or machine

Debian

**Comment by domegabri** [comment]
hi @chrisengel ,

we are planning to add icons for the linux version in the next release!

**Comment by domegabri** [comment]
fixed in 1760b80cea6f609e061313ddc5911a7adb1befc0
