### ISSUE TITLE
SHASUMS file has not been updated for latest release candidate

### ISSUE THREAD

**Issue by niftynei** [Blockstream/green_qt#134]
The SHASUM file uploaded for the latest release has hashes that match the previous release.

https://github.com/Blockstream/green_qt/releases/download/release_2.0.9/SHA256SUMS.asc

**Comment by borgbyte** [comment]
@niftynei can you double check? lgtm here.

**Comment by domegabri** [comment]
I think it was fixed before release 2.0.9 was marked as latest
