### ISSUE TITLE
Restoring a wallet fails on desktop version 2.0.9

### ISSUE THREAD

**Issue by barnzilla** [Blockstream/green_qt#135]
### Description

When I create a wallet, remove the wallet and then restore the wallet, I get a message (`Restoring Your Wallet`) that just hangs forever. The wallet is never restored. 

### Version

Blockstream Green v2.0.9

### Steps to reproduce

1. Create a wallet
2. Remove the wallet
3. Restore the wallet

### Expected behaviour

1. Create a wallet
2. Remove the wallet
3. Restore the wallet (success)

### Actual behaviour

1. Create a wallet
2. Remove the wallet
3. Restore the wallet (fails)

### Screenshots

![image](https://github.com/user-attachments/assets/2a8c3183-1481-478d-834d-d8f7fdca43ef)

### Device or machine

OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Microsoft Corporation
System Model:              Surface Laptop 5
System Type:               x64-based PC
BIOS Version:              Microsoft Corporation 12.101.143, 2024-05-17

### Additional information

FYI - I can restore the wallet using the Android version of the app on my phone.

**Comment by borgbyte** [comment]
Can you try 2.0.10?

**Comment by barnzilla** [comment]
I created/removed/restored a software wallet with v2.0.10 and I think the issue is resolved, at least for me. When I restored the wallet, it took maybe half a minute for it to be restored.

Thank you for resolving this!
