### ISSUE TITLE
docker build: move packages in base image

### ISSUE THREAD

**Issue by kargakis** [Blockstream/green_qt#15]
Move [any dependencies installed during build-time](https://github.com/Blockstream/green_qt/blob/ba34b06799250e4a8f2cfd3e254aeba41867bf19/tools/bionic_deps.sh#L13-L23) into the [base image](https://github.com/Blockstream/green_qt/blob/ba34b06799250e4a8f2cfd3e254aeba41867bf19/Dockerfile#L1), otherwise you are missing out one of the main advantages offered by layering docker images properly which is fast build times.

**Comment by greenaddress** [comment]
@kargakis those things are already in the base image. The file is executed in the base image https://github.com/Blockstream/green_qt/blob/master/Dockerfile#L3 used by travis/gitlab.

The problem we have is that building Qt, gdk and all the deps is fairly slow so we may have to move those too as currently travis timesout.

**Comment by kargakis** [comment]
@greenaddress do you have a different image where the wallet gets installed?

**Comment by greenaddress** [comment]
@kargakis we updated the docker image to contain the other dependencies. Closing. Feel free to reopen if needed.
