### ISSUE TITLE
Feature Request: Connect SPV to remote full node 

### ISSUE THREAD

**Issue by tiero** [Blockstream/green_qt#16]
Hi! Thanks for the recent release, nice and sleek.

I would like to ask to allow the desktop app to connect to its own remote/LAN full node as in the mobile app with the SPV wallet feature.

 Cheers

**Comment by domegabri** [comment]
The idea for this app is to have rpc support so that you can run a node locally/remotely as a backend to track coins and use the app as a signer. coming in two weeks(tm)

**Comment by tiero** [comment]
> The idea for this app is to have rpc support so that you can run a node locally/remotely as a backend to track coins and use the app as a signer. coming in two weeks(tm)

Even better than SPV, that would be be great! Thanks for the update

**Comment by domegabri** [comment]
Its now possible to connect to your personal electrum server or ask the chain of headers to an untrusted server to verify merkle proofs. See these options in app settings.
