### ISSUE TITLE
Add new Liquid Securities Account asks for account to be named but you can't name it

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/green_qt#19]
Version 0.0.1-beta7

When I add a new account of type Liquid Securities Account the name text box appears but I cannot enter anything. Clicking save create it with the name 'Liquid Securities Account' - which is fine but I don't think the text box should appear giving the impression it can be named during creation if that isn't the case.

**Comment by alessandro-saglimbeni** [comment]
Thanks for the feedback, we'll be fixing UI bug

**Comment by domegabri** [comment]
fixed
