### ISSUE TITLE
[Question] I can build green qt on Linux Mint?

### ISSUE THREAD

**Issue by vincenzopalazzo** [Blockstream/green_qt#2]
I have tried to build the wallet with the readme instruction but when running this part of the batch file I get this compiling error

```
cd ${BUILDROOT}

export PATH=${QT_PATH}/bin:${PATH}

if [ "${GREENPLATFORM}" = "linux" ]; then
    ${QT_PATH}/bin/qmake ../green.pro CONFIG+=release CONFIG+=x86_64 CONFIG+=qml_release CONFIG+=static QMAKE_CXXFLAGS_RELEASE+=-flto QMAKE_LDFLAGS_RELEASE+=-flto
elif [ "${GREENPLATFORM}" = "windows" ]; then
    ${QT_PATH}/bin/qmake -spec win32-g++ ../green.pro CONFIG+=x86_64 CONFIG+=release CONFIG+=qml_release CONFIG+=static TARGET_BIT=m64
elif [ "${GREENPLATFORM}" = "osx" ]; then
    ${QT_PATH}/bin/qmake ../green.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=release CONFIG+=qml_release CONFIG+=static QMAKE_CXXFLAGS_RELEASE+=-flto QMAKE_LDFLAGS_RELEASE+=-flto QMAKE_MACOSX_DEPLOYMENT_TARGET=10.14
fi

make -j${NUM_JOBS}

if [ "${GREENPLATFORM}" = "linux" ]; then
    sudo python ../tools/symbol-check.py < ${BUILDROOT}/Green
    sudo strip ${BUILDROOT}/Green
elif [ "${GREENPLATFORM}" = "windows" ]; then
    x86_64-w64-mingw32-strip ${BUILDROOT}/release/Green.exe
elif [ "${GREENPLATFORM}" = "osx" ]; then
    strip ${BUILDROOT}/Green.app/Contents/MacOS/Green
fi

```

Error

```
/media/vincenzo/vincenzodev/DevTmp/green_qt/qt-everywhere-src-5.13.1/qtdeclarative/tests/auto/qml/debugger/qqmlpreview/data/broken.qml:32:Expected token `}'
/media/vincenzo/vincenzodev/DevTmp/green_qt/qt-everywhere-src-5.13.1/qtdeclarative/tests/auto/qml/debugger/qqmlpreview/data/broken.qml:32:Expected token `}'
/media/vincenzo/vincenzodev/DevTmp/green_qt/qt-everywhere-src-5.13.1/qt3d/usecases/CleanQmlDream.qml:75:Unexpected token `identifier'
/media/vincenzo/vincenzodev/DevTmp/green_qt/qt-everywhere-src-5.13.1/qt3d/usecases/CleanQmlDream.qml:75:Unexpected token `identifier'
Project ERROR: Plugin lottieqt is missing a classname entry, please add one to the qmldir file.

```

Thanks so much

**Comment by greenaddress** [comment]
@vincenzopalazzo green qt is still in alpha quality but if you want to try it anyhow you may better luck in docker - we use ubuntu 18.04 for builds - is linux mint based on ubuntu or debian?

Do you have some older qt dev packages installed?

**Comment by vincenzopalazzo** [comment]
@greenaddress The linux mind is based on Ubuntu and Debian [the official reference](https://www.linuxmint.com/about.php).

> Do you have some older qt dev packages installed?
Yes.

Don't worry, I will try to the Docker, if it not work I will try to create a Virtual machine.

Some questions on the command for work with docker.

The command is:

-  `docker build --tag=green_qt .`

- `docker run green_qt`

If the my command is wrong, can you give me the command correct? I'm a beginner with docker

**Comment by farmerwampum** [comment]
I am getting same error, when trying to build on fresh Ubuntu 18.04 VM
`Project ERROR: Plugin lottieqt is missing a classname entry, please add one to the qmldir file.`

**Comment by domegabri** [comment]
there were changes to the build in the past week. retry and let us know if you need any help.

**Comment by vincenzopalazzo** [comment]
Hi @domegabri,

Thank you, I will try and I let know the result.

**Comment by vincenzopalazzo** [comment]
Hi @domegabri,

I ran the actual version on master branch with the command below and it worked, thank you.

`git clone https://github.com/Blockstream/green_qt.git`

`cd green_qt`

`docker run -v $PWD:/ga greenaddress/ci@sha256:d0484f3fe4d0acdc83ba17f8799b957502be90996dbd386900db5851f964e92b /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux && cp /docker_bld_root/build-linux-gcc/Green /ga/Green"`
