### ISSUE TITLE
Unable to restore wallet using QR code scanner.

### ISSUE THREAD

**Issue by KayBeSee** [Blockstream/green_qt#20]
### Description

Unable to restore wallet using QR code scanner. I am trying to import a wallet using the QR code scanner but it's not working. The QR scanner opens up, appears to recognize my QR code, closes but then doesn't populate the mnemonic fields.

### Version

3.3.5

### Steps to reproduce

1) Open Green Wallet
2) Click "..." in top right corner
3) Click "Restore temporary wallet"
4) Click QR Icon in Top Right
5) Scan QR code from https://iancoleman.io/bip39/#english
6) Nothing....

### Expected behaviour

1) Open Green Wallet
2) Click "..." in top right corner
3) Click "Restore temporary wallet"
4) Click QR Icon in Top Right
5) Scan QR code from https://iancoleman.io/bip39/#english
6) Mnemonic words are populated on form
7) Click Restore
8) Able to access and view funds in wallet

### Actual behaviour

1) Open Green Wallet
2) Click "..." in top right corner
3) Click "Restore temporary wallet"
4) Click QR Icon in Top Right
5) Scan QR code from https://iancoleman.io/bip39/#english
6) Nothing....

### Device or machine

iPhone

**Comment by domegabri** [comment]
@KayBeSee it appears you are having issues for the iPhone app, while this repository is for the desktop application. The correct repository is https://github.com/Blockstream/green_ios


On your issue: Blockstream green is compatible with wallets created with blockstream green apps, so you cannot restore a mnemonic generated somewhere else at this point in time.
