### ISSUE TITLE
Linux Build Instructions Fail

### ISSUE THREAD

**Issue by chrisengel** [Blockstream/green_qt#22]
### Description

I try to follow the build.md instructions for Linux and one of the commands fails.

It would be helpful if there was a list of all dependencies as well as even a pre-built .appImage one can use to run Green.

### Steps to reproduce

Go to https://github.com/Blockstream/green_qt/blob/master/BUILD.md

follow instructions: clone repo

then do next step:

sudo ./tools/bionic_deps.sh

And on this step it fails.

### Expected behaviour

I expect the step to succeed so I can finish build instructions.

### Actual behaviour

on this I get the error:

./tools/bionic_deps.sh: line 4: /qtversion.env: No such file or directory

I can then no longer proceed

### Screenshots

![image](https://user-images.githubusercontent.com/12490915/82155009-3587b000-9872-11ea-9553-a441ec6f7c96.png)

### Device or machine

Ubuntu 20.04 LTS, Gnome 3.36.1, X11, Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 , 16gb ram

### Additional info

It is a fresh Ubuntu installation and I have a lot of essential build tools already installed, as well as qt.

**Comment by domegabri** [comment]
Hi, thanks for reporting. we are going to improve docs because they are lacking some new developments on the build process.

**Comment by greenaddress** [comment]
@chrisengel it may be easier to build with docker.

You can either build the docker image yourself:

`docker build . -t selfbuilt`

`docker run -v $PWD:/ga selfbuilt /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux && cp /docker_bld_root/build-linux-gcc/Green /ga/Green"`

 or you can use our pre-built:

`docker run -v $PWD:/ga greenaddress/ci@sha256:d0484f3fe4d0acdc83ba17f8799b957502be90996dbd386900db5851f964e92b /bin/sh -c "cd /ga && ./tools/buildgreen.sh linux && cp /docker_bld_root/build-linux-gcc/Green /ga/Green"`

**Comment by greenaddress** [comment]
instructions have been updated, closing, feel free to reopen if you have any issue or feedback!
