### ISSUE TITLE
When restoring Liquid wallet with invalid seed there is no error displayed in GUI

### ISSUE THREAD

**Issue by chrisengel** [Blockstream/green_qt#23]
### Description

I input 24 word bitcoin wallet seed to mistakenly restore Liquid wallet and when clicking "Continue" button it shows for 500ms or so a loading wheel on the bottom left, but then does nothing

### Version

release_0.0.1-beta7

### Steps to reproduce

Generate a bitcoin seed, then restore Liquid wallet using bitcoin seed, and it just does nothing when trying to Continue

### Expected behaviour

I expect some kind of error saying "Invalid seed" or "No wallet info to restore" or even "Error: are you sure this is a Liquid wallet?"

### Actual behaviour

For a split second the loading wheel in bottom left of the app shows but then nothing happens: no message no nothing.

### Screenshots

![image](https://user-images.githubusercontent.com/12490915/82155495-9c5a9880-9875-11ea-817a-4b65d8c65840.png)

### Device or machine

Ubuntu 20.04 LTS, Gnome 3.36.1, X11, Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 , GeForce GTX 1050 Ti/PCIe/SSE2, 16gb ram

### Additional info

terminal in background shows this:

```
connection change Wallet::Connecting  ->  Wallet::Connected
authentication change Wallet::Unauthenticated  ->  Wallet::Authenticating
[2020-05-17 19:43:10.438848] [0x00007f790ffff700] [info]    Load db, no file or bad file /home/username/.local/share/Blockstream/Green/gdk/0deb9d6b9e2fa49744446e8fe3cc123b7.sqliteaesgcm
authentication change Wallet::Authenticating  ->  Wallet::Unauthenticated
```

It would be nice also once a user has entered seed that they can shift between Bitcoin and Liquid so it doesnt require a total re-entering

**Comment by alessandro-saglimbeni** [comment]
Thanks for reporting, will be adding the appropriate error in one of the next few releases

**Comment by leshik** [comment]
@domegabri @alessandro-saglimbeni
Well, it doesn't even matter if the seed is invalid – it doesn't work with the valid one too. I stumbled upon #26, then tried restoring with this newly created seed, but to no luck. Deleting `~/Library/Application Support/Blockstream/Green` doesn't help either.

**Comment by domegabri** [comment]
@leshik when you say ` a valid one` you mean one generated by Blockstream Green apps?

**Comment by leshik** [comment]
@domegabri yes, the seed that was generated by Green before it crashed.

**Comment by domegabri** [comment]
The seed you are talking about, dis you went through all the steps up to seeing the wallet dashboard with this seed? Generating the secret words is not enough to create the wallet.

**Comment by domegabri** [comment]
The app now throws the `Invalid mnemonic` error in case users type an invalide mnemonic and click the continue button.
