### ISSUE TITLE
Liquid address too long for address input in "Send" window

### ISSUE THREAD

**Issue by chrisengel** [Blockstream/green_qt#24]
### Description

When inputting the address to send to a Liquid address, the input box is not wide enough to show the full address. It is mitigated by having the "review" step for sending, but still why not just make it wide enough to show the whole address.

### Version

release_0.0.1-beta7

### Steps to reproduce

In an active Liquid wallet go to "Send" and enter a real Liquid address

### Screenshots

![image](https://user-images.githubusercontent.com/12490915/82155888-3e7b8000-9878-11ea-9ae8-e98a17da9d33.png)

**Comment by domegabri** [comment]
fixed in b518301a964d0a9a6effbf6c903e4e59d32646ed
