### ISSUE TITLE
No option to make Liquid transactions Non-CT

### ISSUE THREAD

**Issue by chrisengel** [Blockstream/green_qt#25]
### Description

Sometimes there is a usecase for sending L-BTC or other Liquid assets as normal, non-confidential transactions.  Currently there is no option in the Green UI to mark a transaction as non-CT. It could appear either as a checkbox or in an advanced tab with additional potential options

### Version

release_0.0.1-beta7

### Screenshot

![image](https://user-images.githubusercontent.com/12490915/82156097-76cf8e00-9879-11ea-97d9-fb5eb17383e7.png)

**Comment by domegabri** [comment]
Hi, our liquid wallet libraries only create confidential transactions at the time. We haven't had many requests for this feature at the moment so we are not considering it at the moment. A different feature is allowing interested parties to unblind transactions for auditing/escrow purposes (e.g. Bisq) which is something we'll work on.
