### ISSUE TITLE
SHA256SUM does not match

### ISSUE THREAD

**Issue by RaulRider** [Blockstream/green_qt#27]
### WARNING
Release 0.0.1 Green Wallet desktop. SHA256SUM.asc for GreenQt_MacOSX_x86_64.zip does not match.

**Comment by greenaddress** [comment]
thank you @RaulRider for catching this

Looks like a mistake on our part, we modified the osx zip to perform an osx specific notarization process (see https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow ) and by mistake the zip gpg signed was before this notarization process. The next release should fix this.

Attaching the file as per gpg signed hash so you can binary diff them if you want.
[GreenQt_MacOSX_x86_64_correct.zip](https://github.com/Blockstream/green_qt/files/4668028/GreenQt_MacOSX_x86_64_correct.zip)

**Comment by greenaddress** [comment]
Note that the version *without* the notarization process will likely give a warning when running the app the first time

**Comment by greenaddress** [comment]
@RaulRider this has been fixed https://github.com/Blockstream/green_qt/releases/tag/release_0.0.2

Thanks. Closing.
