### ISSUE TITLE
Bech32 support yet?

### ISSUE THREAD

**Issue by maltokyo** [Blockstream/green_qt#28]
As titles suggests. Looks like Bech32 not supported. In this day and age.

**Comment by leishman** [comment]
Same. I was trying to figure out how to generate Bech32 deposit addresses and did not see this option.

**Comment by RolfHodl** [comment]
In the same boat - why no native start?

**Comment by kastravec** [comment]
+1

**Comment by Transisto** [comment]
> In the same boat - why not begin with a native address? Hope this gets added soon.

I'm guessing because having multiple address types ads some complexity there's still a lot of retarded wallets and some exchanges like blockchain_info that don't support sending to BC1 addresses.

There's not that much saving for native vs compatible segwit.

**Comment by domegabri** [comment]
This is now available in singlesig wallets.
