### ISSUE TITLE
GAUTH not working

### ISSUE THREAD

**Issue by leishman** [Blockstream/green_qt#29]
### Description

When I try to setup GAUTH 2FA on my desktop green wallet the form to confirm that I am able to generate proper TOTP codes does not submit.

### Version

0.0.2

### Steps to reproduce

1. Create wallet
2. Go to settings/security
3. Toggle GAUTH for Two-Factor Authentication
4. Save the secret to your google authenticator app
5. Click next
6. In the form that says "Please provide your gauth code." enter the code from your app and click "Next".
7. You will see that nothing happens

### Expected behaviour

The form should submit and indicate that gauth has been setup.

### Actual behaviour

Nothing happens

### Screenshots

![image](https://user-images.githubusercontent.com/3648618/82761044-7587ef00-9dac-11ea-9b63-a07439fd0df5.png)

### Device or machine

MacOS Mojave

**Comment by domegabri** [comment]
Hi @leishman, thanks for the report! Looks like you are typing a 7 digits code while the Google authenticator form expects a 6 digit code. We'll make this more clear in the UI with different components. Besides this we had other user having troubles using it becuse the app is not showing an error when codes are invalid. I believe that is what you encountered here.

**Comment by leishman** [comment]
The screenshot is just a fake code I’m showing. I typed in the actual 6 digit code and it had the same issue. 

>

**Comment by domegabri** [comment]
This was fixed long ago! I hope you were able to use Google Authenticator. Thanks for reporting the bug :)
