### ISSUE TITLE
Build fails from Docker

### ISSUE THREAD

**Issue by bstin** [Blockstream/green_qt#3]
### Description

Trying to build from docker, but build fails at final steps. 
It appears that qt, gdk are built successfully but then fails trying to actually build Green itself.

Any ideas on what I can do to debug further?  

Final failure is:
```
/tmp/ccy84Won.ltrans6.ltrans.o: In function `QSSGRenderPrefilterTextureCPU::build(void*, int, QSSGRenderTextureFormat)':
<artificial>:(.text+0x1dc18): undefined reference to `__wrap_log2f'
collect2: error: ld returned 1 exit status
Makefile:880: recipe for target 'Green' failed
make: *** [Green] Error 1

```
### Version
```
cat .git/refs/heads/master 
923dfddf54449409d9b90cd7d4c58542f58b690c
```

### Steps to reproduce

1. Created docker container
2. checked out green_qt repo and subs
3. Launched docker container, mounting green_qt as /green_qt
4. From within docker container (bash), ran ``./tools/builddeps.sh linux``
The above error appeared (after several pages of 'warnings')

**Comment by kargakis** [comment]
Worked fine for me at ba34b06799250e4a8f2cfd3e254aeba41867bf19
