### ISSUE TITLE
Connect personal node?

### ISSUE THREAD

**Issue by thibistaken** [Blockstream/green_qt#30]
It would be great to have a way to connect a node running on my own hardware for better privacy.

**Comment by RolfHodl** [comment]
Also like this idea - and make tor an opt out option for later in the settings please if your network changes where TOR is blocked.

**Comment by Furunodo** [comment]
duplicate of https://github.com/Blockstream/green_qt/issues/16

**Comment by domegabri** [comment]
yes, I left an answer in #16. Definitely a goal after support for single signature wallets

**Comment by domegabri** [comment]
You can now connect to your personal electrum server.
