### ISSUE TITLE
asset SEND dialog error "[JSON.EXCEPTION... KEY 'BTC' NOT FOUND]" when no L-BTC in wallet

### ISSUE THREAD

**Issue by philippem** [Blockstream/green_qt#31]
### Description

When sending an issued asset from a wallet that has no L-BTC available, the message "[JSON.EXCEPTION.OUT_OF_RANGE.403] KEY 'BTC' NOT FOUND" appears at the bottom of the dialog.

### Version

- Green QT Version 0.0.1 macOS 10.14.6

### Steps to reproduce

1. Transfer asset to empty Green QT wallet, Main Account
2. Click "SEND" from Main Account
3. Add a valid receipientLiquid Address
4. Select issued asset
5. Enter numerical amount

### Expected behaviour

A message to the effect of "inadequate L-BTC for transaction"

### Actual behaviour

Internal error message "[JSON.EXCEPTION.OUT_OF_RANGE.403] KEY 'BTC' NOT FOUND" 

### Screenshots

<img width="1396" alt="green-qt-20200528-no-lbtc" src="https://user-images.githubusercontent.com/565792/83184645-98810e80-a0de-11ea-9dad-437f3af3d08c.png">

### Device or machine

macOS 10.14.6

**Comment by domegabri** [comment]
marked as a bug, thanks for reporting

**Comment by domegabri** [comment]
@philippem thanks for reporting this bug. We have improved the UX and we are not showing the error anymore. The send button is not disabled. We might want to add a tooltip telling the user he needs to receive funds to be able to send.

**Comment by domegabri** [comment]
fixed
