### ISSUE TITLE
pgp key

### ISSUE THREAD

**Issue by Ethqone** [Blockstream/green_qt#36]
Which pgp key is used with the signed shasum file?

**Comment by domegabri** [comment]
Hi, you can find it in the FAQs here: https://greenaddress.it/en/faq.html, in the security section

We are updating our new documentation at https://docs.blockstream.com/green/support.html to have all info in one place.

**Comment by domegabri** [comment]
Documentation updated with PGP fingerprint: https://docs.blockstream.com/green/verify.html
