### ISSUE TITLE
Doesn't run on Win10 clean install

### ISSUE THREAD

**Issue by th3m** [Blockstream/green_qt#39]

**Comment by domegabri** [comment]
Hi, the app should run when running the Green.exe file without requiting additional dependencies.

**Comment by th3m** [comment]
Well i am still facing the problem, i even tried to run it inside the Windows Sandbox without success.

**Comment by domegabri** [comment]
I wasn't able to reproduce this problem. You don't get any error from the system? Not even the smartscreen dialog with the options "Don't run" and "Run anyway" ?

**Comment by cybrox** [comment]
Looked into this a little bit after setting up an old machine for testing some wallet software..

I don't think it's a permission issue on Windows. It does bring up the Don't Run/Run anyways dialog at first but you can confirm that. Also, it may flag the `.exe` and prevent execution but you can also just uncheck that in the properties as usual and it proceeds to launch.

As @th3m noted, it does actually create its directory in AppData and some cache files. For me, it shows the main window for around a second without actually rendering anything in it (white screen) and then crashes. I tried to download and run it on another system that already has quite a lot of software on it and it works without any issues there.

So for reproduction, I think your best bet would be to install Windows on a virtual machine and try to run it without installing anything else first.

**Comment by borgbyte** [comment]
Please try latest version 1.2.3. If you still face issues try running the app with the environment variable `QT_QUICK_BACKEND=software`.

**Comment by borgbyte** [comment]
Please run the latest version.
