### ISSUE TITLE
Cannot restore Liquid wallet

### ISSUE THREAD

**Issue by rbensberg** [Blockstream/green_qt#4]
### Description

Cannot restore Liquid wallet - app hangs after clicking continue

### Version

release_0.0.1-beta1

### Steps to reproduce

Input 24 word seed, clcik continue

### Expected behaviour

Expected to restore succesfully

### Actual behaviour

Hangs. Logs:

qt.qpa.fonts: Populating font family aliases took 237 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost.
connection change Wallet::Disconnected  ->  Wallet::Connecting
[2020-02-21 17:06:21.289594] [0x0000700004a32000] [info]    Connecting using version 111e507e16c2d1f7078a808fd87d79581aa9fc4b to wss://liquidwss.greenaddress.it/v2/ws
connect result 0 QJsonObject({"log_level":"info","name":"liquid","use_tor":false})
NOW CONNECTED
connection change Wallet::Connecting  ->  Wallet::Connected
authentication change Wallet::Unauthenticated  ->  Wallet::Authenticating
[2020-02-21 17:07:56.766963] [0x0000700004a32000] [info]    sqlite loaded correctly /Users/[]/Library/Application Support/Blockstream/Green/gdk/0e70e8403df7e417b98465a73ec7fe15f.sqliteaesgcm

### Screenshots

![image](https://user-images.githubusercontent.com/14806988/75025376-ab77b780-54cd-11ea-8dfe-d7352a07ceb2.png)

### Device or machine

macOS Catalina 10.15.3

**Comment by domegabri** [comment]
this should be fixed. let us know if you can still reproduce

**Comment by rbensberg** [comment]
Looks good thanks.
