### ISSUE TITLE
wallet locked for 435 days

### ISSUE THREAD

**Issue by jasonbrown1965** [Blockstream/green_qt#43]
### Description

"Your wallet is locked for a Two-Factor Authentication reset. The reset will be completed in 435 days" - message under notifications. Authentication options won't respond.

### Version

0.0.3

### Steps to reproduce

Open desktop app on Win10. 

### Expected behaviour

To be able to use app.

### Actual behaviour

App balances can be seen, but cannot send, receive coin, or authenticate app, or turn on two-step or other options. Tried to restore wallet and successfully accessed seed words, but that created a new wallet - did not restore.  

### Screenshots

![image](https://user-images.githubusercontent.com/11400799/95516253-764bb580-0a1b-11eb-8249-ba1bfe83b74f.png)

### Device or machine

PC laptop, Win10 all updates, malwarebytes checked 

### Additional info

Tried cancelling Two Factor reset but no code received.

**Comment by jgriffiths** [comment]
Hi @jasonbrown1965 Can you please contact support via one of the mechanisms listed in https://docs.blockstream.com/green/support.html ? I will close this issue but you can include a link to it when you contact support to save you having to type ithe details out again. We don't provide support via github issues, although we will raise an issue to fix if a bug is found as a result of your support request.

Please include in your support request whether or not you requested a two factor reset on the wallet in addition to the other requested information on the link above, thanks.
