### ISSUE TITLE
Unable to setup GAUTH

### ISSUE THREAD

**Issue by kastravec** [Blockstream/green_qt#44]
### Description

Trying to activate GAUTH fails with the an error "id_inconsistent_data_provided_for" - see the screenshot

### Version

latest release 0.0.8

### Steps to reproduce

This is reproducible each time I try to activate the GAUTH !
i use the Microsoft Authenticator app instead of the Google one, but that shouldn't make a differrence.

Settings -> Security -> Two-factor Authentication -> Enable GAUTH 

Scan the QR code with the microsoft auth and the error appears.

### Expected behaviour

Enable the GAUTH.

I already use a wallet with activated GAUTH and using microsoft auth app. 

### Actual behaviour

Error message 

### Screenshots

<img width="667" alt="Screenshot 2020-12-25 at 16 00 46" src="https://user-images.githubusercontent.com/1362/103137696-6a42cc00-46cb-11eb-99ff-1a961f1aeb97.png">

### Device or machine

macOS Big Sur 11.1

**Comment by LuanEduardo47** [comment]
It's happening with me too. Version 0.0.9

**Comment by domegabri** [comment]
Hello guys and thanks for reporting this. I was able to reproduce as well. Do you guys have other 2FA methods enabled other than Gauth?

**Comment by kastravec** [comment]
No, it's a new wallet created and I wanted to setup only the Gauth, no other 2FA are setup.

**Comment by domegabri** [comment]
a fix for this was introduced in commit 330a8daa8eb3d715bf07d9a18b82442cd3bc6282, will be available in the next release. Let's keep this open until we can get confirmation this is fixed.

**Comment by kastravec** [comment]
Thanks for the fix. I will send my update after trying the next release

**Comment by kastravec** [comment]
Tested the latest release, 0.1.0 and can confirm this issue is resolved. Thanks.

Side note: The new UI enhancements look great and more intuitive
