### ISSUE TITLE
Text in buttons hard to read and in other places

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/green_qt#49]
The text in the Managed Assets (sub account) button is especially hard to read. Seems too thin in most places apart from left menus where the bolder text reads fine.

version 1,0
Ubuntu 19.10
Resolution 1920*1080p

Can hardly read the Managed Assets - white on pale green and very thin font:

![Screenshot from 2021-02-24 12-34-03](https://user-images.githubusercontent.com/25693053/109001582-03c33580-769d-11eb-8eee-9e4e033416fa.png)

Top right text - hard to read and a bit too thin to be clearly edged. Menus on left look fine:

![Screenshot from 2021-02-24 12-36-04](https://user-images.githubusercontent.com/25693053/109001595-0a51ad00-769d-11eb-96ff-bdf28eb5ae63.png)

Also red text (unconfirmed) looks smudged - too thin:

![Screenshot from 2021-02-24 12-40-03](https://user-images.githubusercontent.com/25693053/109002029-94017a80-769d-11eb-9a22-69ab161d5da9.png)

**Comment by domegabri** [comment]
fixed in 0.1.1
