### ISSUE TITLE
Clicking off wallet creation pop up at any point cancels whole sign up process.

### ISSUE THREAD

**Issue by wintercooled** [Blockstream/green_qt#51]
version 1,0 on ubuntu 19.10

It would be nice if the sign up screen remained where it was until you actively choose to cancel out of it. An accidental click off the 'pop up' sign up screen onto the background screen just ditches the whole process, annoying if mnemonic has already been recorded etc.

**Comment by domegabri** [comment]
Fixed in version 0.1.1
