### ISSUE TITLE
Add support for signing messages

### ISSUE THREAD

**Issue by lclc** [Blockstream/green_qt#54]
### Description

I'd like to sign messages.

### Version

Latest release

### Screenshots

Electrum signing as example:
<img width="605" alt="grafik" src="https://user-images.githubusercontent.com/1846033/114063071-817f8100-9898-11eb-8db3-96e1bfddca29.png">

### Additional info

Signing in Core: https://github.com/bitcoin/bitcoin/blob/master/src/util/message.cpp#L56

Signing in Edge:
https://github.com/EdgeApp/edge-currency-bitcoin/blob/49cd76db05256d9ae3cfe0662db708bf43b7a329/src/utils/coinUtils.js#L89-L104

**Comment by borgbyte** [comment]
@lclc you can sign messages with latest release (just with singlesig)

**Comment by borgbyte** [comment]
@lclc closing this, please reopen if you find any issue.
