### ISSUE TITLE
Add signed .asc files and public key for verification of downloads

### ISSUE THREAD

**Issue by karozagorus** [Blockstream/green_qt#56]
### Description

It is not enough to just verify the SHA256 of the file, we need an additional ASC file and a public key that can be easily downloaded and checked against the downloaded files to verify their originality.

**Comment by domegabri** [comment]
See this post in our help center on how you can download the public key from key servers and verify downloads: https://help.blockstream.com/hc/en-us/articles/900002174043-How-do-I-verify-the-Blockstream-Green-binaries-

Let us know if this works for you. Thanks.

**Comment by bitcoin3us** [comment]
Do you have any plans going forward to sign with the Blockstream key, rather than the '.it GreenAddress key', reference: "GreenAddress Team <info@greenaddress.it>"?

According to your website your PGP is referenced here: https://blockstream.com/pgp.txt. This key differs to the key used to sign the Blockstream Green files.

**Comment by domegabri** [comment]
@bitcoin3us the key to verify binaries for blockstream green is the one referenced in the guide I linked above. There is no plan to switch to the one you referenced.

**Comment by Marc-Gee** [comment]
Thanks for having the the post up about how to verify the authenticity of the download. however, to make it less daunting, I suggest that you should include the PGP Public Key file with your releases files. 
That inclusion will make the verification :

- consistent to how most other software releases have their public key easily accessible in 2024.
- It can then function easily with Sparrow Wallet's new _verify downloads_ feature. 
- most people do not know how to make a PGP Public key file. 

@Bitcoin3us - FYI - you should not use/rely on the email address reference of any public key to determine who it belongs to. (confusing as that particular greenaddress is. ). its not a verified address.  Instead you must check the public key ID to a known good published location/website. 

Thx!
M

**Comment by hgs-sellis** [comment]
This page is not accessible https://help.blockstream.com/hc/en-us/articles/900002174043-How-do-I-verify-the-Blockstream-Green-binaries-
