### ISSUE TITLE
Unable to complete reproducible build

### ISSUE THREAD

**Issue by achow101** [Blockstream/green_qt#59]
While following the [build instructions](https://github.com/Blockstream/green_qt/blob/release_0.1.12/BUILD.md) for 0.1.12, I was unable to complete the build. The error was

```
cp: cannot stat '/docker_bld_root/build-linux-gcc/Green': No such file or directory
```

**Comment by borgbyte** [comment]
Sorry about that. The binary was built but with a different name, fixed in 482f222231b10cd9e0d819cbd7897fa81b08bc04.
