### ISSUE TITLE
Crash when restoring Liquid wallet

### ISSUE THREAD

**Issue by samsonmow** [Blockstream/green_qt#6]
### Description

Crash when restoring Liquid wallet

### Version
beta1 

### Steps to reproduce

Launch app
Restore Green wallet
Pick Liquid
Enter words
Click around
Crash

### Device or machine

MacOS latest

**Comment by domegabri** [comment]
this should be as of latest release: https://github.com/Blockstream/green_qt/releases/tag/release_0.0.1-beta5
