### ISSUE TITLE
feed.xml segmentation fault

### ISSUE THREAD

**Issue by petabyt** [Blockstream/green_qt#60]
I kept getting a segmentation fault when I opened the app. I narrowed the issue down to the feed.xml file,  
deleting it fixed the issue.

feed.xml: https://danielc.dev/filedump/feed.xml
Running on:
```
Release 20.04.3 LTS (Focal Fossa) 64-bit
Kernel Linux 5.11.0-34-generic x86_64
MATE 1.24.0
Thinkpad x240
```

Version used: https://greenupdate.blockstream.com/desktop/1.0.0/BlockstreamGreen-x86_64.AppImage

**Comment by borgbyte** [comment]
Update to 1.2.3, this has been fixed in a previous version.
