### ISSUE TITLE
Portable function

### ISSUE THREAD

**Issue by fcore117** [Blockstream/green_qt#62]
Simple request please, add a way to use Green QT portable mode somehow on all platforms (win, linux). This is amazing c++ wallet which is quite rare for these type wallets(that do not store full blockchain). Everyone has gone crazy with Nodejs and Electron bloatware.

**Comment by domegabri** [comment]
Hello @fcore117 , Green Qt already runs on Windows, macOS and Linux. Please let us know if you are having troubles running the app.
