### ISSUE TITLE
Creating a liquid wallet doesn't work. "Creating wallet..." forever

### ISSUE THREAD

**Issue by stopfeds** [Blockstream/green_qt#64]
### Description

Unfortunately, I didn't manage to create liquid wallet on Desktop App. Once I go through the seed wallet steps, after completing the seed phrase check, it says "Creating wallet..." for ages.

### Version

Current
Windows 1.0.4

### Steps to reproduce

Create a liquid wallet, choose either 12 or 24 seed words, write them down, complete the check and continue.
Loading screen appears.

### Expected behaviour

Liquid Wallet gets created, the same as I can create Bitcoin wallets

### Actual behaviour

"Creating wallet..." doesn't end although it says "Connected" in the lower left corner.

### Screenshots

![image](https://user-images.githubusercontent.com/71401614/146083066-dd92e30b-98cd-4160-8b08-0664563a7641.png)

### Device or machine

Windows 10, pretty good specs, no issues with other wallets and applications. Internet connection is perfectly fine.

### Additional info

I created Bitcoin wallets without issues, even received funds. Also tried to re-install Blockstream Green.
I also tried to cancel the process and recover the seed words, didn't work. Similar outcome, it just loads and then it stops and I can try to recover again.

Thanks for your help.

**Comment by stopfeds** [comment]
Still not working... any suggestions?

**Comment by domegabri** [comment]
can you paste the last few lines of your log files? You can find the location of the log file in app settings.

**Comment by borgbyte** [comment]
@stopfeds can you try latest release?
