### ISSUE TITLE
System Message - Test Message

### ISSUE THREAD

**Issue by mercurytoxic** [Blockstream/green_qt#65]
### Description

System message contains "Test Message"

### Version

1.0.4

### Steps to reproduce

Every time I open a Bitcoin testnet account from a Jade Wallet, the account was created in Android Green.

### Expected behaviour

Non empty/useful System message with confirmation box.

### Actual behaviour

I got a popup that says:

_System Message
Test message 1 20211014
I confirm I have read and understood the above message_

### Screenshots

![Screenshot from 2021-12-21 17-14-00](https://user-images.githubusercontent.com/739809/146881228-17b573a4-b84c-4da9-a8f5-62fa50d7d2a2.png)

### Device or machine

Archlinux
CPU: Quad Core Intel Core i5-2500K (-MCP-) speed/min/max: 3137/1600/3700 MHz Kernel: 5.15.7-arch1-1 x86_64

**Comment by jgriffiths** [comment]
Hi @mercurytoxic we use testnet to test, including pushing system messages to ensure the clients display and ack them correctly. That is why the message text is non-meaningful.

You should only see test system messages that were pushed by us after wallet creation. If you are seeing system messages immediately after creating a wallet, please reopen and let us know.
