### ISSUE TITLE
UI Suggestion

### ISSUE THREAD

**Issue by MarioGibney** [Blockstream/green_qt#7]
Ubuntu 18.04.3 LTS
Green 0.0.1

It should be more visible at-a-glance which two-factor methods are enabled or not. You have to look closely to distinguish “enable” from “disable”. Also, it’s not really clear whether or not which ones are on and which are off.

(That is, the option to ‘enable’ can easily be mistaken for the status of ‘disabled’)

![Screenshot from 2020-02-21 17-53-29](https://user-images.githubusercontent.com/22239865/75084160-18da1700-54d3-11ea-859f-95b3a5e4b073.png)

**Comment by domegabri** [comment]
done in 
77156c2
