### ISSUE TITLE
libffi on last AppImage 

### ISSUE THREAD

**Issue by 21btc** [Blockstream/green_qt#72]
AppImage  version 1.1.3 is not working on Ubuntu Jammy Jellyfish (or 22.04) due to an issue with libffi (version 1.1.2 work well on the same os)

```
./BlockstreamGreen-x86_64.AppImage: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory
```
Actual version of libffi is 8.1.0 on my os.

```
find /usr/lib -name "libffi.so*"
/usr/lib/x86_64-linux-gnu/libffi.so.8.1.0
/usr/lib/x86_64-linux-gnu/libffi.so.8
/usr/lib/x86_64-linux-gnu/libffi.so
/usr/lib/i386-linux-gnu/libffi.so.8.1.0
/usr/lib/i386-linux-gnu/libffi.so.8
```

**Comment by domegabri** [comment]
can you download again and retry? We have fixed the version of the appImage builder in our CI and binaries have been updated.

**Comment by 21btc** [comment]
Yes i do. Last version is working well on 22.04. Thanks!
