### ISSUE TITLE
Can't verify the Blockstream Green binaries

### ISSUE THREAD

**Issue by mamolas** [Blockstream/green_qt#74]
Docs describes how to verify the signature
https://help.blockstream.com/hc/en-us/articles/900002174043-How-do-I-verify-the-Blockstream-Green-binaries- 

but the releases are missing the PGP signature file (.sig) to verify the binaries

```
$ gpg --verify SHA256SUMS.asc BlockstreamGreen-x86_64.AppImage

gpg: not a detached signature
```

**Comment by bloodgroup-cplusplus** [comment]
I tried the two steps from the documentation on a mac (apple silicon) and it verified with a few warnings 
Import the public key:

gpg --keyserver keyserver.ubuntu.com --recv-keys "04BE BF2E 35A2 AF2F FDF1 FA5D E7F0 54AA 2E76 E792"


Verify the signed hashes of the downloaded binaries:

gpg --verify SHA256SUMS.as

![Screen Shot 2022-08-21 at 22 59 24](https://user-images.githubusercontent.com/81256027/185803499-b0848523-271f-4925-a1c9-2bd0cc4410bb.png)

**Comment by bitcoin3us** [comment]
When I run the command:
gpg --keyserver keyserver.ubuntu.com --recv-keys "04BE BF2E 35A2 AF2F FDF1 FA5D E7F0 54AA 2E76 E792"

I get the following response:
gpg: keyserver receive failed: No route to host

I'm running a Mac on Apple Silicon. Is there something I'm missing?
