### ISSUE TITLE
With a Jade wallet, the Desktop UI should avoid asking for the user's seed phrase

### ISSUE THREAD

**Issue by strangebit** [Blockstream/green_qt#78]
When you use Green Desktop with a Jade wallet, the user interface makes it much too easy and simple for a newbie to type their seed phrase into their computer. It practically invites you to do it. See my screenshots here:

![1](https://user-images.githubusercontent.com/11712728/206907326-f22b1d67-7ae0-4030-987b-33843d8ca144.png)
![2](https://user-images.githubusercontent.com/11712728/206907329-c74aeba6-34f4-4688-ab42-3bef03fec658.png)
![3](https://user-images.githubusercontent.com/11712728/206907330-a6dac209-346e-471c-b50e-6585306a59ac.png)

A newbie would not realize that he/she isn't supposed to do that. It's assuming that the user has the prerequisite knowledge that they shouldn't do it, rather than the software itself defending against the user doing it.

I grant that there may be some circumstances when a user would want to restore their Jade's wallet on a desktop computer, say if their Jade malfunctions and they need to access their funds quickly, and they are willing to risk doing that. However, a user should probably be doing this because they know that seed phrases are interoperable across many different wallets, and they can therefore restore it into a regular Green wallet if they want. The above user-interface flow that I have shown isn't about that in my opinion.

In the above screenshots, the user-interface flow from a user simply clicking on their 'Recently used' wallet, to typing their seed phrase in when it asks the user, is very quick and immediate. In fact, it's the only thing that the user can do after clicking on their 'Recently used wallet'. It is not obvious enough to a newbie user that it is probably not what they want to be doing, and that it could be dangerous for them. I would expect spoof wallet malware that is trying to target hardware wallet users to have this kind of user-interface flow, by tricking them — with a not unreasonable operating assumption they may have — that the user is supposed to input their seed phrase whenever the software asks for it.

It seems to be merely a vestigial feature from regular Desktop Green wallets, where one is expected to type the seed phrase into their computer for those. The `PIN ACCESS DISABLED` screen is what you see when you have input the wrong PIN three times in a regular Green wallet. So Green should probably recognize when a wallet is a Jade wallet (which it already seems to know), and basically never prompt the user for the seed phrase at all in that case, nor even show this `PIN ACCESS DISABLED` screen (since in the context of using the Jade, I think it doesn't even make sense, and is therefore just confusing to see).

Maybe the UI is different if I have my Jade already connected to my computer when I click this, I don't know. But, if my Jade is not plugged in, it definitely does not mean that it should just ask for my Jade's seed phrase so liberally.

**Comment by bitcoinhelp** [comment]
Totally agree. We actually have a change for this that I believe will be coming in the next Green upgrade - which will prompt the user to plug in Jade instead of saying PIN access disabled. They'll be able to "unlock" their wallet directly from that screen instead of needing to navigate to the current entry point

Appreciate you taking the time to write this up and confirming that this change is crucial

**Comment by strangebit** [comment]
@bitcoinhelp Oh right, that sounds like an appropriate change! Very good! 👍 I will just close this issue then.
