### ISSUE TITLE
Delays on v1.1.8 only when Bluetooth turned on - Windows 10

### ISSUE THREAD

**Issue by lundy405** [Blockstream/green_qt#81]
### Description

Any interaction with the app contains major delays when bluetooth is turned on.  Any clicks take multiple seconds to respond, even closing.  I've tried re-installing previous versions and the issue goes away.  As soon as I install v1.1.8 the issue returns.

### Version

1.1.8

### Steps to reproduce

Install v1.1.8

### Expected behaviour

When you click on things, stuff happens right away.

### Actual behaviour

When you click on things, it ignores you for a few seconds before doing anything.  It's like it's constantly scanning for Bluetooth devices.  As soon as bluetooth is turned off, the performance returns to normal.  Same thing on multiple Win10 Devices.

### Device or machine

Up to date Win 10, Ryzen 7 3800x, 48GB RAM

**Comment by borgbyte** [comment]
This is awkward, can you check 1.2.0?

**Comment by borgbyte** [comment]
@lundy405 I was able to reproduce the issue. Should be fixed in the next release.
