### ISSUE TITLE
Individual BTC transaction values

### ISSUE THREAD

**Issue by Barbaracus** [Blockstream/green_qt#91]
Would it be possible to see the $$ value of each transaction on the windows app.

Using the iPhone app I can click on each transaction and see the BTC amount in dollars.

Using the Windows desktop app I can't therefore I have to copy the btc amount and put the amount in to a 3rd party BTC > dollar exchange website.

I understand it will not be 100% correct and you can choose which exchange site you want to use as the exchange rate.

But it would be nice to be able see the transaction value in $$ not just BTC (like on the app).

**Comment by borgbyte** [comment]
Available in 1.2.7.
