### ISSUE TITLE
Duplicate transactions

### ISSUE THREAD

**Issue by polaco1977** [Blockstream/green_qt#93]
### Description

Duplicate transactions shown

### Version

Green Wallet Desktop version 1.2.6 for Mac

### Steps to reproduce

Contacted Support about this. They gave me this workaround: Remove the folder named "gdk" from "Data Directory" and restart the application.
It worked. The transactions were displayed correctly. But then when I changed the wallet name and restarted the application a second time, the transactions were duplicated again.

Update: Exporting transactions will show them correctly on the csv file.

###

### Actual behaviour

4 hours after writing this issue, the following happened:
1) I labeled each transaction (the original and duplicate transaction were updated at the same time), and
2) I closed the application WITHOUT having previously logged out of the session.
3) After 3 hours, I opened the application, entered the PIN and now the transactions are displayed correctly.

### Screenshots

![imagen](https://github.com/Blockstream/green_qt/assets/142069396/e81a4756-daaf-454b-83cc-c1e973f2a158)

### Device or machine

Macbook Air M1 (2020) MacOs Ventura 13.5.1

**Comment by borgbyte** [comment]
Should be fixed in 1.2.8, please update.
