### ISSUE TITLE
Liquid BTC Wallet Singlesig on JADE, balance does not update

### ISSUE THREAD

**Issue by goodc0re** [Blockstream/green_qt#94]
### Description

L-BTC wallet balance does not update after receiving L-BTC tx

### Version

1.2.7 on MacOS

### Steps to reproduce

Create a L-BTC Singlesig wallet using Blockstream JADE. Receive L-BTC. 

### Expected behaviour

After L-BTC Assets have been received / confirmed, wallet balance should update.

### Actual behaviour

There is no way to get the L-BTC balance to update and display the correct amount, except logging out of the wallet and back in. 

### Device or machine

MacOS 13.4

### Additional info

Network setting Connect with Tor is enabled

**Comment by borgbyte** [comment]
Should be fixed in 1.2.8, please update.
